export const PREFIX = 'j!';

export const COLORS = {
	PRIMARY: 0x2ecc71,
	SECONDARY: 0x8e44ad,
	INFO: 0x0891eb,
	WARNING: 0xf1c40e,
	ERROR: 0xe74c3c
};

export const EMOJIS = {
	TRASH: '🗑'
};

export const SHARDING = false;

export const DEVELOPMENT = process.env.NODE_ENV === 'development';

export const PRODUCTION = process.env.NODE_ENV === 'production';

export const OWNER_ID = '252829167320694784';

export enum TOPICS {
	UNHANDLED_REJECTION = 'UNHANDLED_REJECTION',
	DISCORD = 'DISCORD',
	DISCORD_AKAIRO = 'DISCORD_AKAIRO',
	MONGO_DB = 'MONGO_DB'
}

export enum EVENTS {
	INIT = 'INIT',
	ERROR = 'ERROR',
	READY = 'READY',
	RELOAD = 'RELOAD',
	WARN = 'WARN',
	DEBUG = 'DEBUG',
	COMMAND_STARTED = 'COMMAND_STARTED',
	COMMAND_BLOCKED = 'COMMAND_BLOCKED',
	COMMAND_FINISHED = 'COMMAND_FINISHED',
	COMMAND_CANCELLED = 'COMMAND_CANCELLED',
	SHARD_RESUMED = 'SHARD_RESUMED',
	SHARD_RECONNECTING = 'SHARD_RECONNECTING',
	SHARD_DISCONNECTED = 'SHARD_DISCONNECTED'
}
